#include "stdlib.h"
#include "stdio.h"
#include "rawdisk.h"
#include "allocator.h"

uint8_t* buffer;

void create_data()
{
    for(unsigned int i = 0; i < BYTES_PER_BLOCK; i++)
    {
        buffer[i] = (uint8_t)(i % 256);
    }
}


void clear_buffer()
{
    for(unsigned int i = 0; i < BYTES_PER_BLOCK; i++)
    {
        buffer[i] = 0;
    }
}


// autogenerated func below
void print_hex(const uint8_t *data, size_t len) {
    printf("\n============\n");
    for (size_t i = 0; i < len; i++) {
        printf("%02x ", data[i]);
    }
    printf("\n============\n");
}

void format()
{
    clear_ref_blocks();
    clear_inode_blocks();
    format_super_block();
    // add other format commands here for the upper layers.
}

int main(int argc, char** argv)
{

    printf("Number of total blocks: %u\n", DISK_SIZE_IN_BLOCKS);
    printf("Number of bytes per block: %u\n", BYTES_PER_BLOCK);
    printf("Number of INODE blocks: %u\n", INODE_BLOCKS);
    printf("Number of Reference blocks: %u\n", REF_BLOCKS);
    printf("Number of Data Blocks: %u\n", DATA_BLOCKS);
    printf("Super block position: %u\n",SUPER_BLOCK);
    printf("Reference base block: %u\n", REFERENCE_BASE_BLOCK);
    printf("Inode base block reference: %u\n", INODE_BASE_BLOCK);
    printf("Data base block: %u\n", DATA_BASE_BLOCK);

    int result = open_disk("/dev/vdb");

    printf("Result on opening disk: %s\n", raw_disk_error_to_string(result));
    if(result < 0)
    {
        exit(1);
    }

    create_buffer(&buffer);
    clear_buffer();

    // check if disk formatted.
    bool val = allocator_check_valid_super_block();
    // put other checks here for the upper layers.
    if(!val)
    {
        printf("Disk not formatted as FrostByte FS. Reformatting...\n");
        format();
    }
    close_disk();


    result = open_disk("/dev/vdb");
    printf("Result on opening disk the second time: %s\n", raw_disk_error_to_string(result));
    if(result < 0)
    {
        free_buffer(buffer);
        exit(1);
    }

    // check if disk formatted.
    val = allocator_check_valid_super_block();
    // put other checks here for the upper layers.
    if(!val)
    {
        printf("Disk not formatted as FrostByte FS. Exiting...\n");
        free_buffer(buffer);
        exit(1);
    }

    
    create_data();

    // write test.
    uint32_t block_number;
    int r = write_to_next_free_block(buffer, &block_number);
    printf("Wrote data to data block %u\n",block_number);
    printf("Result: %s\n", allocator_error_to_string(r));

    // read test
    clear_buffer();
    r = read_data_block(buffer, block_number);
    printf("Read data block %u\n",block_number);
    printf("Result: %s\n", allocator_error_to_string(r));
    print_hex(buffer, BYTES_PER_BLOCK);

    // free the block.
    r = free_data_block(block_number);
    printf("Result: %s\n", allocator_error_to_string(r));

    // Try reading again.
    r = read_data_block(buffer, block_number);
    printf("Read data block %u\n",block_number);
    printf("Result: %s\n", allocator_error_to_string(r));

    // try freeing again
    r = free_data_block(block_number);
    printf("Result: %s\n", allocator_error_to_string(r)); 

    // try out of bounds
    r = read_data_block(buffer, DATA_BLOCKS);
    printf("Read data block %u\n",DATA_BLOCKS);
    printf("Result: %s\n", allocator_error_to_string(r));   

    // use ALL of space
    create_data();
    for(uint32_t i = 0; i < DATA_BLOCKS; i++)
    {
        r = write_to_next_free_block(buffer, &block_number);
        printf("Wrote data to data block %u\n",block_number);
        printf("Result: %s\n", allocator_error_to_string(r));
    }

    // try writing again!
    r = write_to_next_free_block(buffer, &block_number);
    printf("Wrote data to data block %u\n",block_number);
    printf("Result: %s\n", allocator_error_to_string(r));

    // do some frees.
    for(uint32_t i = 0; i < DATA_BLOCKS; i += 8)
    {
        r = free_data_block(i);
        printf("Freed data to data block %u\n",i);
        printf("Result: %s\n", allocator_error_to_string(r));
    }

    r = write_to_next_free_block(buffer, &block_number);
    printf("Wrote data to data block %u\n",block_number);
    printf("Result: %s\n", allocator_error_to_string(r));


    // debug out
    clear_buffer();
    printf("Reference block data - Block 0: \n");
    read_block_raw(buffer, REFERENCE_BASE_BLOCK); // 0
    print_hex(buffer, BYTES_PER_BLOCK);

    printf("Reference block data last - Block -1: \n");
    read_block_raw(buffer, REFERENCE_BASE_BLOCK + REF_BLOCKS - 1); // -1
    print_hex(buffer, BYTES_PER_BLOCK);


    close_disk();
    free_buffer(buffer);

}

