#include "stdlib.h"
#include "stdio.h"
#include "rawdisk.h"

unsigned char buffer_frame[BYTES_PER_BLOCK];

void set_buffer()
{
    for(unsigned int i = 0; i < BYTES_PER_BLOCK; i++)
    {
        buffer_frame[i] = (unsigned char)(i % 256);
    }
}


// autogenerated func below
void print_hex(const unsigned char *data, size_t len) {
    for (size_t i = 0; i < len; i++) {
        printf("%02x", data[i]);
    }
    printf("\n");
}

int main(int argc, char** argv)
{
    int result = open_disk("/dev/vdb");

    printf("Result: %s\n", raw_disk_error_to_string(result));
    if(result < 0)
    {
        exit(1);
    }

    set_buffer();
    write_block_raw(buffer_frame, 0);
    close_disk();

    result = read_block_raw(buffer_frame, 0);
    printf("Result: %s\n", raw_disk_error_to_string(result));

    result = open_disk("/dev/vdb");
    printf("Result: %s\n", raw_disk_error_to_string(result));
    if(result < 0)
    {
        exit(1);
    }
    set_buffer();
    read_block_raw(buffer_frame, 0);
    close_disk();

    print_hex(buffer_frame, BYTES_PER_BLOCK);


}